# 支付宝支付相关参数

# 应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
alipay.app-id=9021000132653703

# 商户PID,卖家支付宝账号ID
alipay.seller-id=2088721023509661

# 支付宝网关
alipay.gateway-url=https://openapi-sandbox.dl.alipaydev.com/gateway.do

# 商户私钥，您的PKCS8格式RSA2私钥
alipay.merchant-private-key=MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCX67XVL/QRFK2/pxCdcmykyeKFC8u2A35DOk9UpDQen16CkRCH6OSscvZPVdzorNA/N/Fa2ABp716H9IMoj6CA/CERkiWU1ysG6Z0IlDb6kpPOdHm3jJNQc9b3XUErX9NMtIG2N8919wTuozuG40F+aoX0YkaNokY88+/VBaIrDV0rmMjeXw1WTSkL9cncjJ6ekAocNw41fkhNVNTMACQTA4+bEb7UZf2c8lLXoaWsz8aj4KaMkMFbtWtxDXbQFwt1+Nmf1h8kUUpBAPqX8h5H7mJ4c0QyhVnYtAcatUPulX87ta30UdvIsTCpxF7K73bnHt6JNgfHiNq10iXIaugJAgMBAAECggEAOaJ7zlAt+NjufboEzKafXvkUTcNG2luC6EBT3lmZSFDPyxr7uYP6VQ4cMcbyUvdU3db8Yql1prrgExYJODcc/jIo3YCjb08eDLZOE/Ye0XsQRg/cKW1Uaf44fInNcoYdJImKeDW+KBO5tEsLB0ZqD2qcPTWXbJ42pWMqBpfniQsmS0n3yvrTziNql4E16/ODinzq5Bf49zvgdOHxz6ZbgZ9ODltdTmLJ7xvc8eG42S7uq1TZJlovU4lpW/2hiX17PcEXVMF1foK60hE3qo2/1jr5x0ucxAnD97vqv+JB1+sIqKy5rVgqmkpkvvN2yuIoaOg7mb7r5PWMj2a9Ni0/PQKBgQDntcF9nDCsd4Zrc7XkTzLqPB1XRm9YdVB165TVww47kk9wf+wjVP1u+RS/6kKTxlGUbtwHO72Y5x/O6ZkDXHQnd10OP3VEQe53tJj5ha2D1lhQyXHfYZtIOa86AZTN13/CMp6Y6av4LaMotmihEXBDM/rKLcxo548Y7JPHDC+PKwKBgQCn2LReH0J1aXTjBeXz+cxUZBc7Rduskw/KUnyOzDxJuMell1PnUriRQaZntzx3Z0sOKBc5FzvF4/6TAtZIPIJQw3kIZ6udYlO8GrZ3NwL66+D3Fc0JLnZQ/ZJvDXtCCjnXj+W1DByY2/aoZXDKJhgCF0b/8IJ9fB3HYKjmnjkrmwKBgCc77nRvcwpw/rDJGf57rppc7XbutUHcM3CUIFKFwa4ymwLoljpxVKxqvqm0Z+uPxBaHIviSlAsE76zgfwlDqWNZYcdc1WVmaJOaX+C4UuYk8DVVttNlOp7jLZl71Q95sudWHOa1gmn2iE8He/Xx9vlaHtgHIzqMIv3MaUVl+dObAoGANUfxWb+KlUL4u+hvatdtKYzsYwB2D35PkOZGa/4hVTW3CrXTCKeVt2ajsGDWbQD5LnFDjff2HYeWlIxeAWhT5ddnYGeobrl740aHjaiE5apjK4xcHgIFxQf5qA8bhYdBfVBMlwBVQ6Dv19z7xO/6xw8klrJ+ed8ghN4GP88STukCgYBOF76+e1FLJeO3RsvlNyxmuAzJ0uJuse6aoLfwaJxQXrfc2jTkIlTT/bTM/EDlKhsFH8J33ka9N6JD/M24lRitHnmipFxO3ZQfJvBsd/sDDcSB4dRnP/DD/XG1pT7phjPk2D6Kf7QGxcETFQ3RTbphQQjPvPVAFqS6Apcnu8RRfA==

# 支付宝公钥,查看地址：https://openhome.alipay.com/platform/keyManage.htm 对应APPID下的支付宝公钥
alipay.alipay-public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjaf4B/HxI1MtNRazVwrM7CWcjXkIT5EP022rmzEfP3IT5LXiD7t8IN4LVFngMh/Vn9txd1UeFTtNhnggOsYZzeTCU6IBOua+fKn+NjnSf6wlYUkCIrkVhwNuJcHYmT+gVDxIY1ehqvnr4PEfIUZ4PVGRQo2T6uzuuEnIGXx8M6iwz1Ih/BJvHv3eQujAgaeGGfUP5ngvf+4Yllsao8ECqMVVtVjZkqfLEPfBA4kP79bqnl2l7+OONy2s92xuTOM+ddYSfUQY0cZswJkCraXnU8HsXbuYOX25jIP9v8HfhKdjQZ6CIfUtN1HziE/vRlxRNtr+ClRqmTw8JDCh1QxN3wIDAQAB

# 接口内容加密秘钥，对称秘钥
alipay.content-key=LGkzeh380tQgQ3u+Ybh+xg==

# 页面跳转同步通知页面路径
alipay.return-url=http://localhost:8080/#/orders

# 服务器异步通知页面路径  需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
# 注意：每次重新启动ngrok，都需要根据实际情况修改这个配置
alipay.notify-url=https://5e66-2409-8a00-6045-ebd0-68b4-5d1a-51e-271a.ngrok-free.app/api/ali-pay/trade/notify





